kind: pipeline
type: docker
name: integration

steps:
  - name: code_analysis
    image: boulundeasv/dotnet-sdk-with-java
    commands:
    - dotnet sonarscanner begin 
    - /k:"easv-devops_week6_SonarQube_AY4NVRQqEVvRW2O60EV8" 
      /d:sonar.host.url="http://sonar.setgo.dk:9000" 
      /d:sonar.token="sqp_e0903f4251e6d48759724bacd9a84fc4a2ed7c78"
      /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
      /d:sonar.qualitygate.wait=true
    - dotnet build --no-incremental
    - dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
    - dotnet sonarscanner end /d:sonar.token="sqp_e0903f4251e6d48759724bacd9a84fc4a2ed7c78"
     